/*****************************************************************************
* Model: heartOfStorm.qm
* File:  ./heartOfStorm.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::heartOfStorm.h} .....................................................*/
#ifndef heartOfStorm_h
#define heartOfStorm_h
#ifdef __cplusplus
extern "C" {
#endif
#include "qhsm.h"    /* include own framework */
#define SIMPLE 0
#define MUTANT 1
#define IMMUNE 2
#define DEAD 3
#define DEFAULT_HP 20
#define DOUBLE_HP 40
#define FLASH_MS 500
#define HP_OK 15
#define HP_BAD 5

typedef struct heartOfStormQEvt {
    QEvt super;
    unsigned int id;
    unsigned int damage;
} heartOfStormQEvt;

/*${SMs::HeartOfStorm} .....................................................*/
typedef struct {
/* protected: */
    QHsm super;

/* public: */
    unsigned int CharHP;
    unsigned int MaxHP;
    QStateHandler StartState;
    unsigned int LastState;
} HeartOfStorm;


enum PlayerSignals {
TICK_SEC_SIG = Q_USER_SIG,

PILL_SIG,
BUTTON_PRESSED_SIG,
PILL_HIT_DOUBLE_SIG,
PILL_HEAL_SIG,
DAMAGE_RECEIVED_SIG,
PILL_RESET_SIG,
BUTTON_LONG_PRESSED_SIG,
KILL_SIGNAL_RECEIVED_SIG,
PILL_MUTANT_SIG,
PILL_IMMUNE_SIG,
PILL_REMOVED_SIG,
PILL_HP_DOUBLE_SIG,

LAST_USER_SIG
};
extern QHsm * const the_heartOfStorm; /* opaque pointer to the heartOfStorm HSM */

/*${SMs::HeartOfStorm_ctor} ................................................*/
void HeartOfStorm_ctor(
    unsigned int HP,
    unsigned int MAxHP,
    unsigned int State);

#ifdef __cplusplus
}
#endif
#endif /* heartOfStorm_h */
