
/*
 * JsonStrings.h
 *
 *  Created on: 2020-07-18-22-34
 *      Author: autogenerated from JSON by Notiel
 */

#pragma once

const char* JsonCfg = "{Reactions:  \
	[{ \
		Name: FeelAri,  \
		Sequence: [{Color: [0, 255, 0]}, {Wait: 1000}] \
	}, \
	{ \
		Name: FeelKaesu,  \
		Sequence: [{Color: [255, 0, 0]}, {Wait: 1000}]  \
	}, \
	{ \
		Name: BeSilent,  \
		Transmit: 0 \
	},  \
	{ \
		Name: FeelNorth,  \
		Sequence: [{Color: [255, 255, 0]}, {Wait: 1000},  \
					 {Color: Off}, {Wait: 1000}]  \
	}, \
	{ \
		Name: FeelNorthStrong,  \
		Sequence: [{Color: [255, 255, 0]}, {Wait: 1000},  \
					 {Color: Off}, {Wait: 1000}, \
					 {Color: [255, 255, 255]}, {Wait: 1000},  \
					 {Color: Off}, {Wait: 1000}]  \
	}, \
	{ \
		Name: FeelSouth,  \
		Sequence: [{Color: [128, 0, 255]}, {Wait: 1000},  \
					 {Color: Off}, {Wait: 1000}] \
	}, \
	{ \
		Name: FeelSouthStrong,  \
		Sequence: [{Color: [128, 0, 255]}, {Wait: 1000},  \
					 {Color: Off}, {Wait: 1000}, \
					 {Color: [255, 255, 255]}, {Wait: 1000},  \
					 {Color: Off}, {Wait: 1000}]   \
	}, \
	{ \
		Name: FeelNorthCursed,  \
		Sequence: [{Color: [255, 255, 0]}, {Wait: 1000},  \
					 {Color: [255, 0, 0]}, {Wait: 1000}, \
					 {Color: Off}, {Wait: 1000}]   \
	}, \
	{ \
		Name: FeelSouthCursed,  \
		Sequence: [{Color: [128, 0, 255]}, {Wait: 1000},  \
					 {Color: [255, 0, 0]}, {Wait: 1000}, \
					 {Color: Off}, {Wait: 1000}]   \
	}, \
	{ \
		Name: NorthAttack, \
		Sequence: [{Color: [255, 255, 0]}, {Wait: 1000}] \
	}, \
	{ \
		Name: SouthAttack, \
		Sequence: [{Color: [128, 0, 255]}, {Wait: 1000}] \
	}, \
	{ \
		Name: Back, \
		VibroType: BrrBrrBrr \
	} \
	], \
	 \
	 \
Lockets:[{ \
		Name: Ari,  \
		Type: 0, \
		Button1: AriNorth, \
		Button2: AriSouth, \
		Button3: Silent, \
		ReactOnPwrOn: FeelAri \
	}, \
	{ \
		Name: Kaesu, \
		Type: 1, \
		Button1: KaesuNorth, \
		Button2: KaesuSouth, \
		Button3: Silent, \
		ReactOnPwrOn: FeelKaesu \
	},  \
	{ \
		Name: North,  \
		Type: 2, \
		ReactOnPwrOn: FeelNorth, \
		Receive:  \
			[{ \
				Source: AriNorth, \
				Reaction: FeelAri, \
				Distance: 12 \
			}, \
			{ \
				Source: KaesuNorth, \
				Reaction: FeelKaesu, \
				Distance: 12 \
			}, \
			{ \
				Source: Silent, \
				Reaction: BeSilent, \
				Distance: 12 \
			}, \
			{ \
				Source: AttackNorth, \
				Reaction: NorthAttack, \
				Distance: 8 \
			}, \
			{ \
				Source: RetreatNorth, \
				Reaction: Back, \
				Distance: 8 \
			} \
			] \
	}, \
	{ \
		Name: StrongNorth,  \
		Type: 3, \
		ReactOnPwrOn: FeelNorthStrong, \
		Button1: AttackNorth, \
		Button2: RetreatNorth, \
		Button3: AttackNorth, \
		Receive:  \
			[{ \
				Source: AriNorth, \
				Reaction	: FeelAri, \
				Distance: 12 \
			}, \
			{ \
				Source: KaesuNorth, \
				Reaction: FeelKaesu, \
				Distance: 12 \
			}, \
			{ \
				Source: Silent, \
				Reaction: BeSilent, \
				Distance: 12 \
			}, \
			{ \
				Source: North, \
				Reaction: FeelNorth, \
				Distance: 6 \
			},	 \
			{ \
				Source: StrongNorth, \
				Reaction: FeelNorthStrong, \
				Distance: 6 \
			},	 \
			{ \
				Source: South, \
				Reaction: FeelSouth, \
				Distance: 6 \
			},	 \
			{ \
				Source: StrongSouth, \
				Reaction: FeelSouthStrong, \
				Distance: 6 \
			},			 \
			{ \
				Source: CursedNorth, \
				Reaction: FeelNorthCursed, \
				Distance: 6 \
			}, \
			{ \
				Source: CursedSouth, \
				Reaction: FeelSouthCursed, \
				Distance: 6 \
			}, \
			{ \
				Source: AttackNorth, \
				Reaction: NorthAttack, \
				Distance: 8 \
			}, \
			{ \
				Source: RetreatNorth, \
				Reaction: Back, \
				Distance: 8 \
			} \
			] \
	}, \
	{ \
		Name: South,  \
		Type: 4, \
		ReactOnPwrOn: FeelSouth, \
		Receive:  \
			[{ \
				Source: AriSouth, \
				Reaction: FeelAri, \
				Distance: 12 \
			}, \
			{ \
				Source: KaesuSouth, \
				Reaction: FeelKaesu, \
				Distance: 12 \
			}, \
			{ \
				Source: Silent, \
				Reaction: BeSilent, \
				Distance: 12 \
			}, \
			{ \
				Source: AttackSouth, \
				Reaction: SouthAttack, \
				Distance: 8 \
			}, \
			{ \
				Source: RetreatSouth, \
				Reaction: Back, \
				Distance: 8 \
			}] \
	}, \
	{ \
		Name: StrongSouth, \
		Type: 5, \
		ReactOnPwrOn: FeelSouthStrong, \
		Button1: AttackSouth, \
		Button2: RetreatSouth, \
		Button3: AttackSouth, \
		Receive:  \
			[{ \
				Source: AriSouth, \
				Reaction: FeelAri, \
				Distance: 12 \
			}, \
			{ \
				Source: KaesuSouth, \
				Reaction: FeelKaesu, \
				Distance: 12 \
			}, \
			{ \
				Source: Silent, \
				Reaction: BeSilent, \
				Distance: 12 \
			}, \
			{ \
				Source: North, \
				Reaction: FeelNorth, \
				Distance: 6 \
			},	 \
			{ \
				Source: StrongNorth, \
				Reaction: FeelNorthStrong, \
				Distance: 6 \
			},	 \
			{ \
				Source: South, \
				Reaction: FeelSouth, \
				Distance: 6 \
			},	 \
			{ \
				Source: StrongSouth, \
				Reaction: FeelSouthStrong, \
				Distance: 6 \
			},	 \
			{ \
				Source: CursedNorth, \
				Reaction: FeelNorthCursed, \
				Distance: 6 \
			}, \
			{ \
				Source: CursedSouth, \
				Reaction: FeelSouthCursed, \
				Distance: 6 \
			}, \
			{ \
				Source: AttackSouth, \
				Reaction: SouthAttack, \
				Distance: 8 \
			}, \
			{ \
				Source: RetreatSouth, \
				Reaction: Back, \
				Distance: 8 \
			}] \
	}, 	 \
	{ \
		Name: CursedNorth,  \
		Type: 6, \
		ReactOnPwrOn: FeelNorthCursed, \
		Receive:  \
			[{ \
				Source: AriNorth, \
				Reaction: FeelAri, \
				Distance: 12 \
			}, \
			{ \
				Source: KaesuNorth, \
				Reaction: FeelKaesu, \
				Distance: 12 \
			}, \
			{ \
				Source: Silent, \
				Reaction: BeSilent, \
				Distance: 12 \
			}, \
			{ \
				Source: AttackNorth, \
				Reaction: NorthAttack, \
				Distance: 8 \
			}, \
			{ \
				Source: RetreatNorth, \
				Reaction: Back, \
				Distance: 8 \
			} \
			] \
	}, \
	{ \
		Name: CursedSouth,  \
		Type: 7, \
		ReactOnPwrOn: FeelSouthCursed, \
		Receive:  \
			[{ \
				Source: AriSouth, \
				Reaction: FeelAri, \
				Distance: 12 \
			}, \
			{ \
				Source: KaesuSouth, \
				Reaction: FeelKaesu, \
				Distance: 12 \
			}, \
			{ \
				Source: Silent, \
				Reaction: BeSilent, \
				Distance: 12 \
			}, \
			{ \
				Source: AttackSouth, \
				Reaction: SouthAttack, \
				Distance: 8 \
			}, \
			{ \
				Source: RetreatSouth, \
				Reaction: Back, \
				Distance: 8 \
			}] \
	} \
]}";

