/*****************************************************************************
* Model: mHoS.qm
* File:  ./mHoS.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::mHoS.h} .............................................................*/
#ifndef mHoS_h
#define mHoS_h
#ifdef __cplusplus
extern "C" {
#endif
#include "qhsm.h"    /* include own framework tagunil version */
#define SIMPLE 0
#define MUTANT 1
#define IMMUNE 2
#define DEAD 3
#define FLASH_MS 500
#define SHORT_FLASH_MS 200
#define VIBRO_MS 300
#define DEATH_TO_S 30

typedef struct mHoSQEvt {
    QEvt super;
    unsigned int id;
    unsigned int value;
} mHoSQEvt;

/*${SMs::MHoS} .............................................................*/
typedef struct {
/* protected: */
    QHsm super;

/* public: */
    unsigned int CharHP;
    unsigned int MaxHP;
    unsigned int DefaultHP;
    unsigned int ScaleStep;
    unsigned int LastState;
	QStateHandler StartState;
	unsigned int DeathTime;
} MHoS;

enum PlayerSignals {
TICK_SEC_SIG = Q_USER_SIG,

UPDATE_HP_SIG,
BUTTON_PRESSED_SIG,
PILL_SIG,
PILL_HP_DOUBLE_SIG,
PILL_HEAL_SIG,
DAMAGE_RECEIVED_SIG,
PILL_RESET_SIG,
TIME_TICK_1S_SIG,
BUTTON_LONG_PRESSED_SIG,
PILL_SURGE_SIG,
KILL_SIGNAL_RECEIVED_SIG,
PILL_IMMUNE_SIG,
PILL_MUTANT_SIG,
PILL_REMOVED_SIG,

LAST_USER_SIG
};
extern QHsm * const the_mHoS; /* opaque pointer to the mHoS HSM */

/*${SMs::MHoS_ctor} ........................................................*/
void MHoS_ctor(
    unsigned int HP,
    unsigned int MaxHP,
    unsigned int DefaultHP, 
    unsigned int State
);

#ifdef __cplusplus
}
#endif
#endif /* mHoS_h */
